---
- name: Add or update repository statistics.
  blockinfile:
    path: "{{repository_volume_config_cluster_path.stdout}}/edu-sharing.override.conf"
    marker: "//{mark} EDU SHARING REPOSITORY STATISTICS"
    insertafter: EOF
    block: |
      // statistics endpoints (for providing public information about content counts, user counts, etc.)
      repository.statistics.api = {
        enabled:{{ edu_enable_statistics_api | default('false',true) }}
      }
