---
- name: register pixabay - add app-pixabay.properties.xml
  become: true
  template:
    src: pixabay.properties.xml
    dest: "{{repository_volume_config_cluster_path.stdout}}/applications/app-pixabay.properties.xml"

- name: register pixabay - edit applicationfiles in ccapp-registry.properties.xml
  become: true
  lineinfile:
    backrefs: yes
    path: "{{repository_volume_config_cluster_path.stdout}}/applications/ccapp-registry.properties.xml"
    line: '<entry key="applicationfiles">\g<start>\g<end>,app-pixabay.properties.xml</entry>'
    regexp: '^\s*<entry key="applicationfiles">(?P<start>(?:(?!,app-pixabay.properties.xml).)*)(,app-pixabay.properties.xml)?(?P<end>.*?)</entry>'
