---
- include_role:
    name: edu-sharing-init
    tasks_from: set_edu_docker_inst_dir
    apply:
      tags:
        - edu-sharing-shibboleth
  tags:
    - edu-sharing-shibboleth

- include_role:
    name: edu-sharing-init
    tasks_from: load_version_variables
    apply:
      tags:
        - edu-sharing-shibboleth
  tags:
    - edu-sharing-shibboleth

- include_role:
    name: edu-sharing-customization
    tasks_from: fetch_docker_paths
    apply:
      tags:
        - edu-sharing-shibboleth
  vars:
    extra_required_paths:
      - "{{repository_volume_config_node_path.stdout}}/defaults/client.config.xml"
      - "{{ repository_config_edu_sharing_path.stdout }}/WEB-INF/classes"
      - "{{ repository_config_edu_sharing_path.stdout }}/WEB-INF/lib"
    store_docker_paths_globally: true
  tags:
    - edu-sharing-shibboleth

- name: Install edu-sharing-shibboleth
  block:
    - include_tasks: unregister.yml
    - include_tasks: register_shibboleth.yml
    - include_tasks: config-env.yml
    - include_tasks: register_shibboleth_client_config.yml
    - include_tasks: register_override_configuration.yml
    - include_tasks: register_shibboleth_after.yml
  when: edu_configure_shibboleth is defined and edu_configure_shibboleth
  tags:
    - edu-sharing-shibboleth

- name: Unregister edu-sharing-shibboleth from edu-sharing.
  block:
    - include_tasks: unregister.yml
  when: edu_configure_shibboleth is defined and not edu_configure_shibboleth
  tags:
    - edu-sharing-shibboleth

- name: Restart edu-sharing in docker.
  command:
    chdir: "{{ edu_docker_inst_dir }}"
    cmd: "{{edu_sharing_restart_command | replace('{service}', 'repository-service') }}"
  no_log: true
  tags:
    - edu-sharing-shibboleth

- include_role:
    name: edu-sharing-init
    tasks_from: wait_services_to_be_up
    apply:
      tags:
        - edu-sharing-shibboleth
  when: "'edu-sharing-shibboleth' in ansible_run_tags"

