---
- name: set shibboleth settings in homeApplication.properties.xml
  become: true
  lineinfile:
    path: "{{repository_volume_config_cluster_path.stdout}}/applications/homeApplication.properties.xml"
    line: '<entry key="{{item[0]}}">{{item[1]}}</entry>'
    regexp: '<entry key="{{item[0]}}">'
    insertbefore: "</properties>"
  loop:
    - ["allowed_authentication_types", "shibboleth"]
