---
edu_sharing_archive_url: https://artifacts.edu-sharing.com/repository/maven-remote/org/edu_sharing/edu_sharing-projects-community-deploy-docker-compose/9.0.0/edu_sharing-projects-community-deploy-docker-compose-9.0.0-bin.zip

# In newer versions Edu-sharing may change the deploy commands, if so we can change them here
# {service} is an variable tha ansible will replace, based on what service we want to execute the action
edu_sharing_deploy_command: 'sg docker -c "./utils.sh start {service}"'
edu_sharing_restart_command: 'sg docker -c "./utils.sh restart {service}"'
# remove docker images from server
edu_sharing_undeploy_command: 'sg docker -c "./utils.sh stop {service}"'
edu_sharing_remove_containers_command: |
     yes | sg docker -c "./utils.sh remove {service}"

# this will remove images,containers and volumes, so be carefully when we use it.
edu_sharing_purge_all_command: |
     yes | sg docker -c "./utils.sh purge {service}"

# Edu-sharing backup command
edu_sharing_backup_command: 'sg docker -c "./utils.sh backup {options}"'
# Edu-sharing restore command
edu_sharing_restore_command: 'sg docker -c "./utils.sh restore {options}"'

service_repository_search_solr:  'repository-search-solr'