---

- name: Update package lists
  apt:
    update_cache: yes

- name: Install java packages
  apt: 
    pkg: "default-jdk"
    state: present 
    update_cache: yes

- include_tasks: get_java_home.yml

- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home
  become: true
  tags:
  - java

