- name: Ensures custom-dir exists
  file: path='{{ edu_docker_inst_dir }}/custom-repository-service' state=directory

- name: get temporary current original container repository-service
  shell: |
    sg docker -c "docker create --name temp-repository-service  {{repository_service_image}}"

- name: copy files and remove temp container
  block:
    - name: get reinstall.sh file from temporary container
      shell:
        chdir: "{{ edu_docker_inst_dir }}/custom-repository-service"
        cmd: |
          sg docker -c "docker cp temp-repository-service:/opt/alfresco/bin/reinstall.sh ."
  always:
    - name: remove temporary container repository-service
      shell: |
        sg docker -c "docker rm temp-repository-service"
