---
- name: modify reinstall.sh script to accept alfviral amp
  blockinfile:
    path: "{{ edu_docker_inst_dir }}/custom-repository-service/reinstall.sh"
    insertbefore: "^libcheck.sh$"
    marker: "# Add alfviral amp file"
    block: |
        if [[ -d amps/alfviral ]] ; then
          echo "[CUSTOM] install alfviral:"
          java -jar bin/alfresco-mmt.jar install amps/alfviral tomcat/webapps/alfresco -directory -nobackup -force
        fi