---
  - name: Copy .env.sample to .env.
    command:
      chdir: "{{ edu_docker_inst_dir }}"
      cmd: "cp -f .env.sample .env"

  - name: Adjust values in .env file.
    lineinfile:
      path: "{{ edu_docker_inst_dir }}/.env"
      state: present
      regexp: "^# {{ item.key }}="
      line: "{{ item.key }}={{ item.value }}"
    no_log: true
    when: item.value is defined and item.value != ""
    loop: "{{ edu_sharing_environment_variable | default([], true) }}"