---

- name: Check if the image exists locally
  shell: |
    sg docker -c "docker images -q {{ repository_service_image | trim }}"
  register: image_check
  changed_when: false

- name: Pull the image if it does not exist
  shell: |
    sg docker -c "docker pull {{ repository_service_image | trim }}"
  when: image_check.stdout | trim == ""
  changed_when: true

- name: Ensures custom-dir exists
  file: path='{{ edu_docker_inst_dir }}/custom-repository-service' state=directory

- name: get temporary current original container repository-service
  shell: |
    sg docker -c "docker create --name temp-repository-service {{repository_service_image | trim}}"

- name: copy files and remove temp container
  block:
    - name: get amp file from temporary container.
      shell:
        chdir: "{{ edu_docker_inst_dir }}/custom-repository-service"
        cmd: |
          sg docker -c "docker cp temp-repository-service:/opt/alfresco/amps/alfresco/1/ ."

    - name: Get amp file name.
      shell:
        chdir: "{{ edu_docker_inst_dir }}/custom-repository-service"
        cmd: |
          mv 1/* .
          ls *.amp | head -n 1
      register: amp_file
      failed_when: false  # Prevent the task from failing if no files are found

    - name: Set fact for the first .amp file.
      set_fact:
         amp_file_name: "{{ amp_file.stdout.strip() if amp_file.stdout.strip() else '' }}"

  always:
    - name: remove temporary container repository-service.
      shell: |
        sg docker -c "docker rm temp-repository-service"

- name: get original files from archive.
  shell:
    chdir: "{{ edu_docker_inst_dir }}/custom-repository-service"
    cmd: "{{ java_home }}/bin/jar xf {{ amp_file_name }} config/alfresco/extension/{{ item.path }}"
  loop: "{{ (alfresco_ccmodel_add_custom_properties | default([], true)) + (edu_cccontentmodel_adjustments | default([], true)) }}"

- include_tasks: alfresco-model.yml
  vars:
    alfresco_extension_path: "{{ edu_docker_inst_dir }}/custom-repository-service/config/alfresco/extension"

- name: update modified files in archive
  shell:
    chdir: "{{ edu_docker_inst_dir }}/custom-repository-service"
    cmd: "{{ java_home }}/bin/jar uf {{ amp_file_name }} config/alfresco/extension/{{ item.path }}"
  loop: "{{ (alfresco_ccmodel_add_custom_properties | default([], true)) + (edu_cccontentmodel_adjustments | default([], true)) }}"

- name: add dockerfile for custom container
  template:
    src: "Dockerfile_repository-service.j2"
    dest: "{{ edu_docker_inst_dir }}/custom-repository-service/Dockerfile_repository-service"

- include_tasks: alfresco_amp_modules.yml

- name: build custom container repository-service
  shell:
    chdir: "{{ edu_docker_inst_dir }}/custom-repository-service"
    cmd: >
      sg docker -c "docker build --no-cache -f Dockerfile_repository-service -t {{ repository_service_image|trim}}-{{ edu_repo_caption }}-custom ."

- name: Allow pull failures to be able to use custom image
  replace:
    path: "{{ edu_docker_inst_dir }}/utils.sh"
    regexp: 'pull \|'
    replace: "pull --ignore-pull-failures |"
  when: edu_version is defined and (edu_version | regex_replace('-RC[0-9]+', '')) is version_compare('8.0.0','>=')
