---
enable_notification_service: false
notification_service_version: 10.0.1
# installation directory
notification_service_install_dir: "{{base_dir}}/notification-service_{{notification_service_version|replace('.','_')}}"

# repository_volume_config_plugins:
#      stdout: '{{notification_service_install_dir}}'
# repository_volume_docker_plugins:
#      stdout: '{{notification_service_install_dir}}'

notification_service_docker_project_name: "notification_service_docker_version"

notification_mail_templates_base_path: "{{notification_service_install_dir}}/templates/mail"

# a list of custom mail templates that should be copied into notification-service; 
# format of each entry: 
#     [<source-file-path>, <destination>]
# example: 
#     - ['baseLayout.html', '/mail/html/baseLayout.html']
notification_mail_templates: