---
- name: Start extracting the content of the .jar file.
  when: enable_notification_service is defined and enable_notification_service and repository_volume_config_plugins.stdout is defined and repository_volume_config_plugins.stdout != ''
  block:
    - name: Ensure plugin-kafka directory exists.
      become: true
      file:
        path: "{{ repository_volume_config_plugins.stdout }}/plugin-kafka"
        state: directory
      tags:
        - edu-sharing-notification

    - name: Download plugin Kafka config .jar file.
      # become: true
      get_url:
        force: yes
        url: "{{ repository_plugin_kafka_config }}"
        dest: "{{ notification_service_install_dir }}/{{ repository_plugin_kafka_config | basename }}"
      tags:
        - edu-sharing-notification

    - name: Extract plugin Kafka config sources.
      become: true
      shell: |
        unzip -o "{{ notification_service_install_dir }}/{{ repository_plugin_kafka_config | basename }}" \
          "plugin-kafka/*" -d "{{ repository_volume_config_plugins.stdout }}/"
      register: unzip_result
      tags:
        - edu-sharing-notification

  rescue:
    - name: Handle failure - perform recovery action.
      debug:
        msg: "The task failed because the condition was false. Performing recovery action."
      tags:
        - edu-sharing-notification

    - name: Rollback changes.
      become: true
      shell: |
        rm -rf {{ repository_volume_config_plugins.stdout }}/plugin-kafka/*
      tags:
        - edu-sharing-notification

  always:
    - name: Clean up the .jar file.
      # become: true
      shell: |
        rm {{ notification_service_install_dir }}/{{ repository_plugin_kafka_config | basename }}
      tags:
        - edu-sharing-notification
