---
- name: Start extracting the content of the .jar file.
  when: enable_notification_service is defined and enable_notification_service and repository_volume_docker_plugins.stdout is defined and repository_volume_docker_plugins.stdout != ''
  block:
    - name: Ensure plugin-kafka directory exists.
      become: true
      file:
        path: "{{ repository_volume_docker_plugins.stdout }}/plugin-kafka"
        state: directory
      tags:
        - edu-sharing-notification

    - name: Download plugin kafka config .jar file.
      get_url:
        force: yes
        url: "{{ repository_plugin_kafka_deploy }}"
        dest: "{{ notification_service_install_dir }}/{{ repository_plugin_kafka_deploy | basename }}"
      tags:
        - edu-sharing-notification

    - name: Extract plugin kafka docker sources.
      become: true
      shell: |
        unzip -o {{notification_service_install_dir}}/{{repository_plugin_kafka_deploy | basename}}  "plugin-kafka/*" -d {{ repository_volume_docker_plugins.stdout }}/
      tags:
        - edu-sharing-notification

  rescue:
    - debug:
        msg: "The task failed because the condition was false. Performing recovery action."
      tags:
        - edu-sharing-notification

    - name: Rollback changes.
      become: true
      shell: |
        rm -rf {{ repository_volume_docker_plugins.stdout }}/plugin-kafka/*
      tags:
        - edu-sharing-notification

  always:
    - name: Clean up the .jar file.
      # become: true
      file:
        path: "{{ notification_service_install_dir }}/{{ repository_plugin_kafka_deploy | basename }}"
        state: absent
      tags:
        - edu-sharing-notification
