---

- name: Clean Everything First
  become: true
  shell: |
        rm -rf {{notification_mail_templates_base_path}}/*
  when: notification_mail_templates_folder_clean | default(true, true)
  tags:
    - edu-sharing-notification-template-override

- name: Ensure that the directories of files exists.
  become: true
  file:
    path: "{{notification_mail_templates_base_path}}/{{ item[1] | dirname }}"
    state: directory
  loop: "{{ notification_mail_templates | default([], true) }}"
  tags:
    - edu-sharing-notification-template-override


- name: Copy mail templates.
  become: true
  copy:
    # remote_src: yes
    src: "{{item[0]}}"
    dest: "{{notification_mail_templates_base_path}}/{{item[1]}}"
  loop: "{{ notification_mail_templates | default([], true) }}"
  tags:
    - edu-sharing-notification-template-override