---
- name: Get the path to the repository service config plugins.
  shell: |
    sg docker -c "docker volume inspect --format '{{ '{{' }}.Mountpoint{{ '}}' }}'  $(sg docker -c "docker volume ls -q |grep '_repository-service-volume-config-plugins'")"
  register: repository_volume_config_plugins
  ignore_errors: true
  tags:
    - edu-sharing-notification

- name: Get the path to the repository service config plugins.
  shell: |
    sg docker -c "docker volume inspect --format '{{ '{{' }}.Mountpoint{{ '}}' }}'  $(sg docker -c "docker volume ls -q |grep '_repository-service-volume-bin-plugins'")"
  register: repository_volume_docker_plugins
  ignore_errors: true
  tags:
    - edu-sharing-notification

- name: Get the path to the repository service config plugins.
  shell: |
    sg docker -c "docker volume inspect --format '{{ '{{' }}.Mountpoint{{ '}}' }}'  $(sg docker -c "docker volume ls -q |grep '_repository-service-volume-config-edu-sharing'")"
  register: repository_service_volume_edu_sharing
  ignore_errors: true
  tags:
    - edu-sharing-notification

- name: Get the path to the repository service config plugins.
  shell: |
    sg docker -c "docker volume inspect --format '{{ '{{' }}.Mountpoint{{ '}}' }}'  $(sg docker -c "docker volume ls -q |grep '_repository-service-volume-amps'")"
  register: repository_service_volume_amps
  ignore_errors: true
  tags:
    - edu-sharing-notification

- name: Wait until folders are created by Docker.
  become: true
  wait_for:
    path: "{{ item }}"
    state: present
    timeout: 300 # Set a timeout value as needed
  retries: 10
  delay: 10
  loop:
    - "{{ repository_volume_config_plugins.stdout }}"
    - "{{ repository_volume_docker_plugins.stdout }}"
    - "{{ repository_service_volume_amps.stdout }}/alfresco/2/"
    - "{{ repository_service_volume_amps.stdout }}/edu-sharing/1/"
    - "{{ repository_service_volume_edu_sharing.stdout }}/WEB-INF/lib/"
  ignore_errors: true
  tags:
    - edu-sharing-notification
