---
# Used ony if the tomcat is is still there, if we changed the default one then we can override
tomcat_stop_command: "{{base_dir}}/bin/tomcat.sh stop 2> /dev/null || true"

edu_sharing_docker_timezone: '{{timezone | default("Europe/Berlin",true)}}'

edu_sharing_environment_variable:
  - key: COMPOSE_PROJECT_NAME
    value: '{{edu_sharing_docker_project_name}}'
  - key: REPOSITORY_DATABASE_NAME
    value: '{{alfresco_db.name}}'
  - key: REPOSITORY_DATABASE_USER
    value: '{{alfresco_db.user}}'
  - key: REPOSITORY_DATABASE_PASS
    value: '{{alfresco_db.password}}'
  - key: COMMON_BIND_HOST
    value: '{{common_bind_host | default("127.0.0.1",true)}}'
  - key: REPOSITORY_SERVICE_GUEST_USER
    value: '{{guest_user_name | default("esguest",true)}}'
  - key: REPOSITORY_SERVICE_GUEST_PASS
    value: '{{guest_user_password | default("esguest",true)}}'
  - key: REPOSITORY_SERVICE_ADMIN_PASS
    value: '{{alf_password}}'
  - key: SERVICES_RENDERING_DATABASE_NAME
    value: '{{esrender_db.name}}'
  - key: SERVICES_RENDERING_DATABASE_USER
    value: '{{esrender_db.user}}'
  - key: SERVICES_RENDERING_DATABASE_PASS
    value: '{{esrender_db.password}}'


# Edu-sharing-plugin-oersi-update see: gitlab.com/TIBHannover/oer/edu-sharing-plugin-oersi-update

# version of the amp file
es_update_oersi_version: 1.0.3
es_update_oersi_amp_filename: "es-update-oersi-{{es_update_oersi_version}}.amp"
# oersi update endpoint 
es_update_oersi_url: 'https://oersi.org/resources/api-internal/import-scripts/python/update-record'


es_update_oersi_configuration:
  - key: oersi.url
    value: "{{es_update_oersi_url | default('',true)}}"
  - key: edu_sharing.baseUrl
    value: "{{edu_sharing_url | default('',true)}}"
  - key: bulk.thread.pool.size
    value: "{{thread_pool_size | default(200,true)}}"


# antivirus alfviral see: https://github.com/TIBHannover/alfviral
antivirus_alfviral_version: 1.4.0
antivirus_alfviral_amp_filename: 'alfviral-platform-{{ antivirus_alfviral_version }}.amp'

alfviral_antivirus_configuration:
  - key: alfviral.mode
    value: "INSTREAM"
  - key: alfviral.instream.timeout
    value: "{{antivirus_alfviral_timeout | default(10000,true)}}"
  - key: alfviral.instream.host
    value: "{{clamav_proxy}}"
  - key: alfviral.instream.port
    value: "{{antivirus_alfviral_port | default(3310,true)}}"
  - key: alfviral.on_update.delete
    value: "{{ antivirus_alfviral_on_update_delete | default('true',true) }}"
  - key: alfviral.notify.user
    value: "{{ antivirus_alfviral_notify_user | default('true',true)}}"
  - key: alfviral.notify.admin
    value: "{{ antivirus_alfviral_notify_admin | default('true',true)}}"
  - key: alfviral.notify.asynchronously
    value: "{{ antivirus_alfviral_notify_asynchronously | default('false',true) }}"
  - key: alfviral.notify.user.template
    value: "{{ antivirus_alfviral_user_template | default('notify_user_en.html.ftl',true) }}"
  - key: alfviral.notify.admin.template
    value: "{{ antivirus_alfviral_admin_template | default('notify_admin_en.html.ftl',true) }}"
  - key: alfviral.file.exceptions
    value: ""

mail_configuration:
  - key: mail.host
    value: "{{ edu_mail_smtp_server | default('') }}"
  - key: mail.port
    value: '{{ edu_mail_smtp_port | default("25") }}'
  - key: mail.username
    value: '{{ edu_mail_smtp_username | default("") }}'
  - key: mail.password
    value: '{{ edu_mail_smtp_passwd | default("") }}'
  - key: mail.encoding
    value: '{{ edu_mail_smtp_encoding | default("UTF-8",true) }}'
  - key: mail.from.default
    value: '{{ edu_mail_smtp_from | default("pleasechange@nodomain.com") }}'
  - key: mail.smtp.auth
    value: '{{ edu_mail_smtp_auth | default("false") }}'