---
# Used ony if the tomcat is is still there, if we changed the default one then we can override
tomcat_stop_command: "{{base_dir}}/bin/tomcat.sh stop 2> /dev/null || true"

edu_sharing_docker_timezone: '{{timezone | default("Europe/Berlin",true)}}'

edu_sharing_environment_variable:
  - key: COMPOSE_PROJECT_NAME
    value: '{{edu_sharing_docker_project_name}}'
  - key: REPOSITORY_DATABASE_NAME
    value: '{{alfresco_db.name}}'
  - key: REPOSITORY_DATABASE_USER
    value: '{{alfresco_db.user}}'
  - key: REPOSITORY_DATABASE_PASS
    value: '{{alfresco_db.password}}'
  - key: COMMON_BIND_HOST
    value: '{{common_bind_host | default("127.0.0.1",true)}}'
  - key: REPOSITORY_SERVICE_GUEST_USER
    value: '{{guest_user_name | default("esguest",true)}}'
  - key: REPOSITORY_SERVICE_GUEST_PASS
    value: '{{guest_user_password | default("esguest",true)}}'
  - key: REPOSITORY_SERVICE_ADMIN_PASS
    value: '{{alf_password}}'
  - key: SERVICES_RENDERING_DATABASE_NAME
    value: '{{esrender_db.name}}'
  - key: SERVICES_RENDERING_DATABASE_USER
    value: '{{esrender_db.user}}'
  - key: SERVICES_RENDERING_DATABASE_PASS
    value: '{{esrender_db.password}}'
  - key: SERVICES_RENDERING_SERVICE_HOST
    value: '{{edu_sharing_host}}'
  - key: SERVICES_RENDERING_SERVICE_PORT
    value: '{{edu_sharing_port | default("80",true)}}'
  - key:  SERVICES_RENDERING_SERVICE_PORT_HTTP
    value: '{{rendering_service_port_http| default("9100",true)}}'
  - key: SERVICES_RENDERING_SERVICE_PROT
    value: '{{rendering_service_prot| default("http",true)}}'
  - key: SERVICES_RENDERING_SERVICE_GDPR_ENABLED
    value: '{{rendering_service_enable_gdpr| default("false",true)}}'
  - key: SERVICES_RENDERING_SERVICE_GDPR_MODULES
    value: '{{rendering_service_gdpr_modules| default("",true)}}'
  - key: SERVICES_RENDERING_SERVICE_GDPR_URLS
    value: '{{rendering_service_gdpr_urls| default("",true)}}'
  - key: SERVICES_RENDERING_SERVICE_PLUGINS
    value: '{{rendering_service_plugins| default("",true)}}'
  - key: SERVICES_RENDERING_SERVICE_VIEWER_ENABLED
    value: '{{rendering_service_viewer_enabled| default("true",true)}}'
  - key: SERVICES_RENDERING_SERVICE_CACHE_CLEANER_SCHEDULE
    value: '{{ rendering_service_cache_cleaner_schedule | default("0 0 * * 0", true) | quote }}'
  - key: SERVICES_RENDERING_RENDERMOODLE_URL
    value: '{{rendering_service_rendering_module_url| default("",true)}}'
  - key: SERVICES_RENDERING_RENDERMOODLE_TOKEN
    value: '{{rendering_service_rendering_module_token| default("",true)}}'
  - key: SERVICES_RENDERING_RENDERMOODLE_CATEGORY_ID
    value: '{{rendering_service_rendering_module_category_id| default("1",true)}}'
  - key: SERVICES_RENDERING_AUDIO_FORMATS
    value: '{{rendering_service_audio_format| default("mp3",true)}}'
  - key: SERVICES_RENDERING_VIDEO_FORMATS
    value: '{{rendering_service_video_format| default("mp4,webm",true)}}'
  - key: SERVICES_RENDERING_VIDEO_RESOLUTIONS
    value: '{{rendering_service_video_resolutions| default("240,720,1080",true)}}'
  - key: SERVICES_RENDERING_VIDEO_DEFAULT_RESOLUTION
    value: '{{rendering_service_video_default_resolution| default("720",true)}}'