---
# Used ony if the tomcat is is still there, if we changed the default one then we can override
tomcat_stop_command: "{{base_dir}}/bin/tomcat.sh stop 2> /dev/null || true"

edu_sharing_docker_timezone: '{{timezone | default("Europe/Berlin",true)}}'

edu_sharing_environment_variable:
  - key: COMPOSE_PROJECT_NAME
    value: '{{edu_sharing_docker_project_name}}'
  - key: REPOSITORY_DATABASE_NAME
    value: '{{alfresco_db.name}}'
  - key: REPOSITORY_DATABASE_USER
    value: '{{alfresco_db.user}}'
  - key: REPOSITORY_DATABASE_PASS
    value: '{{alfresco_db.password}}'
  - key: COMMON_BIND_HOST
    value: '{{common_bind_host | default("127.0.0.1",true)}}'
  - key: REPOSITORY_SERVICE_GUEST_USER
    value: '{{guest_user_name | default("esguest",true)}}'
  - key: REPOSITORY_SERVICE_GUEST_PASS
    value: '{{guest_user_password | default("esguest",true)}}'
  - key: REPOSITORY_SERVICE_ADMIN_PASS
    value: '{{alf_password}}'
  - key: SERVICES_RENDERING_DATABASE_NAME
    value: '{{esrender_db.name}}'
  - key: SERVICES_RENDERING_DATABASE_USER
    value: '{{esrender_db.user}}'
  - key: SERVICES_RENDERING_DATABASE_PASS
    value: '{{esrender_db.password}}'
  # MongoDB configuration for edu-sharing services
  - key: MONGO_DATABASES_ROOT_USER
    value: '{{mongo_databases.root_user | default("root",true)}}'
  - key: MONGO_DATABASES_ROOT_PASS
    value: '{{mongo_databases.root_pass | default("root",true)}}'
  - key: MONGO_DATABASES_REPLICATION_SET_KEY
    value: '{{mongo_databases.replication_set_key | default("edusharing",true)}}'
  # Rendering2 service database configuration
  - key: RENDERING2_SERVICE_DATABASE_NAME
    value: '{{esrender2.db_name | default("rendering",true)}}'
  - key: RENDERING2_SERVICE_DATABASE_USER
    value: '{{esrender2.db_user | default("rendering",true)}}'
  - key: RENDERING2_SERVICE_DATABASE_PASS
    value: '{{esrender2.db_password | default("rendering",true)}}'
  # LUMI service database configuration
  - key: RENDERING2_LUMI_DATABASE_NAME
    value: '{{esrender2.lumi_db_name | default("lumi",true)}}'
  - key: RENDERING2_LUMI_DATABASE_USER
    value: '{{esrender2.lumi_db_user | default("lumi",true)}}'
  - key: RENDERING2_LUMI_DATABASE_PASS
    value: '{{esrender2.lumi_db_password | default("lumi",true)}}'
    # Notification service database configuration
  - key: NOTIFICATION_SERVICE_DATABASE_NAME
    value: '{{notification_service.db_name | default("notification",true)}}'
  - key: NOTIFICATION_SERVICE_DATABASE_USER
    value: '{{notification_service.db_user | default("notification",true)}}'
  - key: NOTIFICATION_SERVICE_DATABASE_PASS
    value: '{{notification_service.db_pass | default("notification",true)}}'
   # Repository service database configuration
  - key: REPOSITORY_MONGO_DATABASE
    value: '{{plugin_mongo.database_name | default("repository",true)}}'
  - key: REPOSITORY_MONGO_USER
    value: '{{plugin_mongo.database_user | default("repository",true)}}'
  - key: REPOSITORY_MONGO_PASS
    value: '{{plugin_mongo.database_pass | default("repository",true)}}'