---
- name: Copy .env file file.
  template:
    src: .env.j2
    dest: "{{edu_connector_install_dir}}/.env"

- name: Copy override file.
  template:
    src: 3_connector-override-common.yml.j2
    dest: "{{notification_service_install_dir}}/3_connector-override-common.yml"
  vars:
    edu_sharing_docker_network_name: "{{repository_service_docker_network_name.stdout}}"

- name: Copy deploy shell script file.
  template:
    src: deploy.sh.j2
    dest: "{{edu_connector_install_dir}}/deploy.sh"
    mode: "744"

- name: Run edu-sharing-connector.
  shell:
    chdir: "{{edu_connector_install_dir}}/"
    cmd: "{{edu_connector_deploy_command}}"
