---
edu_configure_shibboleth: "{{ install_shibboleth }}" # Activate shibboleth authentication in edu-sharing true|false (if set to false and 'install_shibboleth' to true, you can install shibboleth without activation in edu-sharing)
# allow additional local edu-sharing login, otherwise login redirects directly to 'edu_login_shib_url' 'true'|'false'
edu_login_allow_local: "true"
# the login url that should be used for shibboleth login
edu_login_shib_url: "{{ edu_sharing_url }}/shibboleth"
# configuration of the next two variables allows to login at the IdP directly or at the local edu-Sharing
# example: https://smart.vhb.org/edu-sharing/components/login
# these variables require service endpoints that provide a list of all Shibb-IdPs
# NOTE: this is not implemented here!
#edu_login_providers_url: 'test'
#edu_login_provider_target_url: 'test'

edu_sso_context_path: edu-sharing-sso-context.xml # absolut or relative path to edu-sharing-sso-context.xml

edu_sharing_shibboleth_env_variable:
  - key: REPOSITORY_SERVICE_AUTH_EXTERNAL
    value: '{{ "true"}}'
  - key: REPOSITORY_SERVICE_AUTH
    value: '{{ "shibboleth"}}'
  - key: REPOSITORY_SERVICE_AUTH_EXTERNAL_LOGIN
    value: "{{ shibboleth_sp_protected_path}}"
  - key: REPOSITORY_SERVICE_AUTH_EXTERNAL_LOGOUT
    value: '{{ shibboleth_sp_base_path +"/Shibboleth.sso/Logout?return=" +  edu_sharing_url + "/components/login"}}'
  - key: REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGOUT_DESTROY_SESSION
    value: "true"
  - key: REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGOUT_REDIRECT
    value: '{{ "true"}}'
  - key: REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGOUT_REDIRECT_URL
    value: '{{edu_sharing_url + "/components/login"}}'
