---
- include_role:
    name: edu-sharing-init
    tasks_from: set_edu_docker_inst_dir
    apply:
      tags:
        - edu-sharing-after
  tags:
    - edu-sharing-after

- include_role:
    name: edu-sharing-init
    tasks_from: load_version_variables
    apply:
      tags:
        - edu-sharing-after
  tags:
    - edu-sharing-after

- include_role:
    name: edu-sharing-customization
    tasks_from: fetch_docker_paths
    apply:
      tags:
        - edu-sharing-after
  vars:
    store_docker_paths_globally: true
  tags:
    - edu-sharing-after

- include_role:
    name: edu-sharing-init
    tasks_from: wait_services_to_be_up
    apply:
      tags:
        - edu-sharing-after
  tags:
    - edu-sharing-after

- name: Add/modify configuration
  block:
    - include_tasks: update_edu_sharing_client_config.yml
  tags:
    - edu-sharing-after
