---
- name: Start extracting the content of the .jar file.
  when: enable_plugin_mongo_service is defined and enable_plugin_mongo_service and repository_volume_docker_plugins.stdout is defined and repository_volume_docker_plugins.stdout != ''
  block:
    - name: Ensure plugin-mongo directory exists.
      become: true
      file:
        path: "{{ repository_volume_docker_plugins.stdout }}/plugin-mongo"
        state: directory
      tags:
        - edu-sharing-plugin-mongo

    - name: Download plugin mongo config .jar file.
      get_url:
        force: yes
        url: "{{ repository_plugin_mongo_deploy }}"
        dest: "{{ plugin_mongo_service_install_dir }}/{{ repository_plugin_mongo_deploy | basename }}"
      tags:
        - edu-sharing-plugin-mongo

    - name: Extract plugin mongo docker sources.
      become: true
      shell: |
        unzip -o {{plugin_mongo_service_install_dir}}/{{repository_plugin_mongo_deploy | basename}}  "plugin-mongo/*" -d {{ repository_volume_docker_plugins.stdout }}/
      tags:
        - edu-sharing-plugin-mongo

  rescue:
    - debug:
        msg: "The task failed because the condition was false. Performing recovery action."
      tags:
        - edu-sharing-plugin-mongo

    - name: Rollback changes.
      become: true
      shell: |
        rm -rf {{ repository_volume_docker_plugins.stdout }}/plugin-mongo/*
      tags:
        - edu-sharing-plugin-mongo

  always:
    - name: Clean up the .jar file.
      # become: true
      file:
        path: "{{ plugin_mongo_service_install_dir }}/{{ repository_plugin_mongo_deploy | basename }}"
        state: absent
      tags:
        - edu-sharing-plugin-mongo
