---
- name: Start adding Alfresco .amp file.
  when: enable_plugin_mongo_service is defined and enable_plugin_mongo_service and repository_service_volume_amps.stdout is defined and repository_service_volume_amps.stdout != ''
  block:
    - name: Ensure alfresco folder exists.
      become: true
      file:
        path: "{{ repository_service_volume_amps.stdout }}/alfresco/2/"
        state: directory
      tags:
        - edu-sharing-plugin-mongo

    - name: Download plugin mongo alfresco .amp file.
      become: true
      get_url:
        force: yes
        url: "{{ repository_plugin_mongo_backend_alfresco_module }}"
        dest: "{{ repository_service_volume_amps.stdout }}/alfresco/2/{{ repository_plugin_mongo_backend_alfresco_module | basename }}"
      tags:
        - edu-sharing-plugin-mongo

  rescue:
    - debug:
        msg: "The task failed. Performing recovery action."
      tags:
        - edu-sharing-plugin-mongo

    - name: Rollback changes.
      become: true
      file:
        path: "{{ repository_service_volume_amps.stdout }}/alfresco/2/{{ repository_plugin_mongo_backend_alfresco_module | basename }}"
        state: absent
      tags:
        - edu-sharing-plugin-mongo
