---
- name: Ensures backup_path dir exists
  file: path='{{ backup_path }}' state=directory

- name: Backup alfresco database
  no_log: true
  shell: |
    PGPASSWORD="{{alfresco_db.password}}" pg_dump -h localhost -U {{alfresco_db.user}}  {{alfresco_db.name}}  --serializable-deferrable | gzip > {{backup_path}}/{{alfresco_db.name}}-dump.sql.gz

- name: Add migration for database version = 7
  blockinfile:
    path: "{{ edu_docker_inst_dir }}/3_repository-service-volume-override-common.yml"
    block: |2
        repository-database:
           volumes:
             - "{{ backup_path }}/{{ alfresco_db.name }}-dump.sql.gz:/docker-entrypoint-initdb.d/psqldump.sql.gz"
    insertafter: '^\s*services:$'
    marker: ""
  when: edu_version is defined and (edu_version | regex_replace('-RC[0-9]+', '')) is version_compare('8.0.0','<')

- name: Add migration for database version >=8
  blockinfile:
    path: "{{ edu_docker_inst_dir }}/docker-compose.override.yml"
    block: |2
        repository-database:
           volumes:
             - "{{ backup_path }}/{{ alfresco_db.name }}-dump.sql.gz:/docker-entrypoint-initdb.d/psqldump.sql.gz"
    insertafter: '^\s*services:$'
    marker: ""
  when: edu_version is defined and (edu_version | regex_replace('-RC[0-9]+', '')) is version_compare('8.0.0','>=')

- name: Launch edu-sharing in docker.
  command:
    chdir: "{{ edu_docker_inst_dir }}"
    cmd: "{{edu_sharing_deploy_command}}"
  no_log: true

- name: Get the path to the alfresco docker volume.
  shell: |
    sg docker -c "docker volume inspect --format '{{ '{{' }}.Mountpoint{{ '}}' }}'  $(sg docker -c "docker volume ls -q |grep '_repository-service-volume-data'")"
  register: alfresco_volume_data
  ignore_errors: true

- name: Get stats of the alfresco docker volume
  become: true
  stat:
    path: "{{alfresco_volume_data.stdout}}"
  when: alfresco_volume_data.stdout != ""
  register: alfresco_volume_data_stats

- name: Copy alfresco data  to alfresco volume.
  become: true
  copy:
    src: "{{ alf_home}}/alf_data/"
    dest: "{{alfresco_volume_data.stdout}}"
    mode: "{{alfresco_volume_data_stats.stat.mode}}"
    owner: "{{alfresco_volume_data_stats.stat.uid}}"
    group: "{{alfresco_volume_data_stats.stat.gid}}"
    remote_src: yes
  when: (alfresco_volume_data.stdout is defined and alfresco_volume_data.stdout != "") and 
        (alfresco_volume_data_stats.stat.isdir is defined and alfresco_volume_data_stats.stat.isdir)

- name: Export HAS_EDU_SHARING_DOCKER_MIGRATION_PROCESSED=true to avoid multiple migration
  become: true
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - key: HAS_EDU_SHARING_DOCKER_MIGRATION_PROCESSED
      value: "true"