---
enable_plugin_mongo_service: false
plugin_mongo_service_version: 10.0.1
# installation directory
plugin_mongo_service_install_dir: "{{base_dir}}/mongo-service_{{plugin_mongo_service_version|replace('.','_')}}"


# it must have same docker project name as edu-sharing, otherwise the backup will not work
plugin_mongo_service_docker_project_name: "{{edu_sharing_docker_project_name}}"



mongo_plugin_environment_variable:
  - 'REPOSITORY_MONGO_DATABASE=${REPOSITORY_MONGO_DATABASE:-{{ plugin_mongo.db_name | default("repository", true) }}}'
  - 'REPOSITORY_MONGO_CONNECTION_STRING=${REPOSITORY_MONGO_CONNECTION_STRING:-mongodb://{{ plugin_mongo.db_user | default("repository", true) }}:{{ plugin_mongo.db_pass | default("repository", true) }}@mongo-database:27017/{{ plugin_mongo.db_name | default("repository", true) }}?authSource={{ plugin_mongo.db_name | default("repository", true) }}}'