---

- include_role:
    name: edu-sharing-customization
    tasks_from: fetch_docker_paths
    apply:
      tags:
        - edu-sharing-splash
  vars:
    extra_required_paths:
      - "{{repository_volume_config_cluster_path.stdout}}/edu-sharing.override.conf"
    store_docker_paths_globally: true
  tags:
    - edu-sharing-splash


- name: Download and install edu-sharing-splash
  block:
    - include_tasks: install.yml
    - include_tasks: register_apache.yml
    - include_tasks: register_splash.yml
  when: enable_edu_sharing_splash is defined and enable_edu_sharing_splash
  tags:
    - edu-sharing-splash

- name: Unregister edu-sharing-connector from edu-sharing.
  block:
    - include_tasks: unregister.yml
  when: enable_edu_sharing_splash is defined and not enable_edu_sharing_splash
  tags:
    - edu-sharing-splash