---


- name: Add job for classification keywords
  set_fact:
    classification_keyword_job: > 
         {{ [{'jobClass': 'org.edu_sharing.repository.server.jobs.quartz.ImportFactualTermMarc21', 'params': { 'fileUri': '{{ edu_sharing_protocol | default("http") }}://{{edu_sharing_host}}/{{edu_classification_keyword_path}}' } }] }}


# For edu-sharing docker version we need to wait for responses up to 3 minutes
- name: "wait edu-sharing to come up"
  uri:
    url: '{{ edu_sharing_url }}'
    timeout: 60
    status_code: 200
  register: esresult
  until: esresult.status == 200
  retries: 30
  delay: 10
  when: classification_keyword_job | default([], true) | length>0
  
- name: "get access token"
  uri:
    url: '{{ edu_sharing_url }}/oauth2/token'
    method: POST
    body: 'grant_type=password&client_id=eduApp&client_secret=secret&username=admin&password={{ alf_password }}'
    return_content: yes
  register: accesstokenreply
  until: accesstokenreply.status == 200
  retries: 5
  delay: 10
  no_log: true
  when: classification_keyword_job | default([], true) | length>0

- name: "set access token"
  vars:
    jsonVar: '{{ accesstokenreply.content | from_json }}'
  set_fact:
    accesstoken: '{{ jsonVar.access_token }}'
  no_log: true
  when: classification_keyword_job | default([], true) | length>0

- name: "Execute jobs"
  uri:
    url: '{{ edu_sharing_url }}/rest/admin/v1/job/{{ item.jobClass }}'
    method: POST
    body_format: json
    headers:
      Authorization: 'Bearer {{ accesstoken }}'
      Accept: application/json
    body: '{{ item.params }}'
  no_log: true
  loop: '{{ classification_keyword_job | default([], true) }}'
  loop_control:
    pause: 5
  when: classification_keyword_job | default([], true) | length>0
