---
- name: Install cron package
  become: true
  apt:
    name: 
      - cron
    update_cache: true
    state: "present"
  tags:
  - packages
  - edu-sharing-mirror-vocabs

- include_tasks: mirror-vocabs.yml
  when: mirror_vocabularies | default([], true) | length>0
  tags: 
    - mirror-vocabularies