
- name: Copy docker-compose.yml.j2 to inst-dir as docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{clamav_docker_install_dir}}/docker-compose.yml"
  tags:
    - edu-sharing-antivirus
    - clamav
    - antivirus-clamav

- name: Run ClamAV Docker container
  shell:
    chdir: '{{clamav_docker_install_dir}}/'
    cmd: "{{clamav_docker_run_command}}"
  tags:
    - edu-sharing-antivirus
    - clamav
    - antivirus-clamav