# -------- Menu entries (BEGIN) --------#
- name: Remove all menuEntries from client config
  xml:
    path: "{{ repository_volume_config_node_path.stdout}}/defaults/client.config.xml"
    xpath: "/config/values/menuEntries"
    state: absent
    pretty_print: yes

- include_tasks: custom_menu_entry.yml
  args:
    apply:
      become: yes  
  with_items: "{{ edu_custom_menu_entries | default([], true) }}"
  when: (repository_config_edu_sharing_path.stdout is defined) and (repository_config_edu_sharing_path.stdout != "")
  loop_control:
    loop_var: custom_menu_entry
# -------- Menu entries (END)-------- #
