---
- name: Include the task file to fetch docker paths and wait for required files
  include_tasks: fetch_docker_paths.yml
  tags:
    - edu-sharing-config-node

- include_tasks: client-configuration.yml
  args:
    apply:
      become: yes
  when: (repository_volume_config_node_path.stdout is defined) and (repository_volume_config_node_path.stdout != "")
  tags:
    - edu-sharing-config-node
