---
- name: Copy mds_override.xml.
  copy:
    src: "{{item}}"
    dest: "{{repository_volume_config_node_path.stdout}}/defaults/metadatasets/xml"
  with_items: "{{edu_mds_override_paths | default([], true) }}"

- name: Copy valuespaces.
  copy:
    src: "{{item}}"
    dest: "{{repository_volume_config_node_path.stdout}}/defaults/metadatasets/xml/valuespaces/"
  with_items: "{{edu_valuespaces_paths | default([], true) }}"

- name: Copy i18n.
  copy:
    src: "{{item}}"
    dest: "{{repository_volume_config_node_path.stdout}}/defaults/metadatasets/i18n/"
  with_items: "{{edu_valuespaces_i18n_paths | default([], true) }}"
