version: "3.7"

services:
  repository-service:
    image: docker.edu-sharing.com/projects/community/edu_sharing-projects-community-deploy-docker-repository-build-service:{{ edu_version }}-{{ edu_repo_caption }}-custom
    volumes:
      - repository-service-volume-config-node:/opt/bitnami/tomcat/shared/classes/config
      - "repository-service-volume-config-edu-sharing:/opt/bitnami/tomcat/webapps/edu-sharing"
      - repository-service-volume-config-plugins:/opt/alfresco/tomcat/shared/classes/config/plugins
      - repository-service-volume-bin-plugins:/opt/alfresco/bin/plugins
      - repository-service-volume-amps:/opt/alfresco/amps

volumes:
  repository-service-volume-config-edu-sharing:
  repository-service-volume-config-plugins:
  repository-service-volume-bin-plugins:
  repository-service-volume-amps:
