FROM {{repository_service_image | regex_replace('[\\n\\t]', '')}}

USER worker
COPY {{amp_file_name}} /opt/alfresco/amps/alfresco/1/{{amp_file_name}}

{% if (activate_es_update_oersi is defined and activate_es_update_oersi) or (install_antivirus is defined and install_antivirus) %}
COPY reinstall.sh /opt/alfresco/bin/reinstall.sh
{% endif %}