---
- name: Update alfresco-global.properties if mail_configuration is not empty
  become: true
  lineinfile:
    path: '{{ alfresco_global_properties_path }}/alfresco-global.properties'
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}={{ item.value }}'
    insertafter: EOF
  loop: "{{ mail_configuration }}"
  when: mail_configuration is defined and mail_configuration | length > 0