---

- name: Update alfresco-global.properties if es_update_oersi_configuration is not empty
  become: true
  lineinfile:
    path: '{{ alfresco_global_properties_path }}/alfresco-global.properties'
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}={{ item.value }}'
    insertafter: EOF
  loop: "{{ es_update_oersi_configuration }}"
  when: es_update_oersi_configuration is defined and es_update_oersi_configuration | length > 0