---
- include_role:
    name: edu-sharing-init
    tasks_from: set_edu_docker_inst_dir
    apply:
      tags:
        - edu-sharing-custom-amp
  tags:
    - edu-sharing-custom-amp

- include_role:
    name: edu-sharing-init
    tasks_from: load_version_variables
    apply:
      tags:
        - edu-sharing-custom-amp
  tags:
    - edu-sharing-custom-amp

- name: Load paths and wait for paths to be generated.
  include_tasks: wait_for_paths.yml
  tags:
    - edu-sharing-custom-amp

# Include download tasks
- name: Download and install required plugins
  block:
    - include_tasks: cleanup.yml
    - include_tasks: download-and-install-alfviral-amp.yml
    - include_tasks: download-and-install-esupdate-oersi-amp.yml
    - include_tasks: configure_alfresco_properties.yml
  tags:
    - edu-sharing-custom-amp

- name: Restart edu-sharing service in docker.
  command:
    chdir: "{{ edu_docker_inst_dir }}"
    cmd: "{{ edu_sharing_restart_command | replace('{service}', notification_service_repository_service | default('repository-service')) }}"
  tags:
    - edu-sharing-custom-amp

- include_role:
    name: edu-sharing-init
    tasks_from: wait_services_to_be_up
    apply:
      tags:
        - edu-sharing-custom-amp
