---

- name: Remove alfviral from alfresco-global.properties
  become: true
  lineinfile:
    path: '{{ alfresco_global_properties_path }}/alfresco-global.properties'
    regexp: '^{{ item.key }}='
    state: absent
  loop: "{{ alfviral_antivirus_configuration }}"
  when: alfviral_antivirus_configuration is defined and alfviral_antivirus_configuration | length > 0

- name: Remove mail from alfresco-global.properties
  become: true
  lineinfile:
    path: '{{ alfresco_global_properties_path }}/alfresco-global.properties'
    regexp: '^{{ item.key }}='
    state: absent
  loop: "{{ mail_configuration }}"
  when: mail_configuration is defined and mail_configuration | length > 0