---
- name: Ensure plugin rendering service 2 installation directory exists
  file:
    path: "{{rendering_service_2_plugin_install_dir}}"
    state: directory
  tags:
    - edu-sharing-rendering-service2

- name: Download compose file.
  get_url:
    force: yes
    url: "{{ repository_rendering_service_2_deploy_docker_compose }}"
    dest: "{{ rendering_service_2_plugin_install_dir }}/{{ repository_rendering_service_2_deploy_docker_compose | basename }}"
  tags:
    - edu-sharing-rendering-service2

- name: Extract docker files.
  become: true
  unarchive:
    remote_src: yes
    src: "{{ rendering_service_2_plugin_install_dir }}/{{ repository_rendering_service_2_deploy_docker_compose | basename }}"
    dest: "{{rendering_service_2_plugin_install_dir}}"
  tags:
    - edu-sharing-rendering-service2

- name: Copy .env file file.
  template:
    src: .env.j2
    dest: "{{rendering_service_2_plugin_install_dir}}/.env"
  tags: 
    - edu-sharing-rendering-service2

- name: Copy deploy shell script file.
  template:
    src: deploy.sh.j2
    dest: "{{rendering_service_2_plugin_install_dir}}/deploy.sh"
    mode: "a+x"
  tags: 
    - edu-sharing-rendering-service2

- name: Get the network name of a container based on a pattern
  shell: |
    sg docker -c "docker inspect --format '{{ '{{json ' }}.NetworkSettings.Networks{{ '}}' }}'  $(sg docker -c "docker ps --filter 'name=repository-service_' --format '{{ '{{' }}.Names{{ '}}' }}' | head -n 1 ") | jq -r 'keys[]'"
  register: repository_service_docker_network_name
  ignore_errors: true
  tags:
    - edu-sharing-rendering-service2

- name: Check edu-sharing version.
  debug:
    msg: "Your edu-sharing version is {{ repository_service_docker_network_name.stdout }}."
  tags:
    - edu-sharing-rendering-service2

- name: Copy override file.
  template:
    src: 2_rendering_service_2-override-common.yml.j2
    dest: "{{rendering_service_2_plugin_install_dir}}/2_rendering_service_2-override-common.yml"
  vars:
    edu_sharing_docker_network_name: "{{repository_service_docker_network_name.stdout}}"
  tags:
    - edu-sharing-rendering-service2

